// Code generated by "stringer -type UiEvent -output gui_event_strings.go"; DO NOT EDIT.

package ui

import "strconv"

const _UiEvent_name = "EVENT_REFRESH"

var _UiEvent_index = [...]uint8{0, 13}

func (i UiEvent) String() string {
	if i < 0 || i >= UiEvent(len(_UiEvent_index)-1) {
		return "UiEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UiEvent_name[_UiEvent_index[i]:_UiEvent_index[i+1]]
}
