// Code generated by "stringer -type UiEvent -output gui_event_strings.go"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EVENT_REFRESH-0]
	_ = x[EVENT_QUIT-1]
}

const _UiEvent_name = "EVENT_REFRESHEVENT_QUIT"

var _UiEvent_index = [...]uint8{0, 13, 23}

func (i UiEvent) String() string {
	if i < 0 || i >= UiEvent(len(_UiEvent_index)-1) {
		return "UiEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UiEvent_name[_UiEvent_index[i]:_UiEvent_index[i+1]]
}
